# 配置合并于 2025-11-12 20:28:15
mixed-port: 7890
tcp-concurrent: false
allow-lan: true
ipv6: true
mode: Rule
log-level: info
global-client-fingerprint: chrome
find-process-mode: strict
external-controller: 0.0.0.0:9090
geodata-mode: true
geo-auto-update: true
geo-update-interval: 3
geox-url:
  geoip: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://mirror.ghproxy.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8800
      override-destination: true
    TLS:
      ports:
      - 443
      - 8443
    QUIC:
      ports:
      - 443
      - 8443
  skip-domain:
  - Mijia Cloud
  - dlg.io.mi.com
  - +.apple.com
tun:
  enable: false
  stack: mixed
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - cable.auth.com
  - +.msftconnecttest.com
  - +.msftncsi.com
  - network-test.debian.org
  - detectportal.firefox.com
  - resolver1.opendns.com
  - +.srv.nintendo.net
  - +.stun.playstation.net
  - xbox.*.microsoft.com
  - +.xboxlive.com
  - stun.*
  - global.turn.twilio.com
  - global.stun.twilio.com
  - localhost.*.qq.com
  - +.logon.battlenet.com.cn
  - +.logon.battle.net
  - +.blzstatic.cn
  - +.cmpassport.com
  - id6.me
  - open.e.189.cn
  - mdn.open.wo.cn
  - opencloud.wostore.cn
  - auth.wosms.cn
  - +.jegotrip.com.cn
  - +.icitymobile.mobi
  - +.pingan.com.cn
  - +.cmbchina.com
  - +.cmbchina.com.cn
  - pool.ntp.org
  - +.pool.ntp.org
  - ntp.*.com
  - time.*.com
  - ntp?.*.com
  - time?.*.com
  - time.*.gov
  - time.*.edu.cn
  - +.ntp.org.cn
  - time.*.apple.com
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  nameserver-policy:
    www.baidu.com: 114.114.114.114
    +.internal.crop.com: 10.0.0.1
    www.baidu.com,+.google.cn: https://doh.pub/dns-query
    geosite:private,apple: https://dns.alidns.com/dns-query
    rule-set:google: 8.8.8.8
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://1.1.1.2/dns-query
  - https://1.0.0.2/dns-query
  - https://208.67.222.222/dns-query
  - https://208.67.220.220/dns-query
  - https://9.9.9.9/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
    - gfw
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
    domain:
    - +.google.com
    - +.github.com
    - +.facebook.com
    - +.twitter.com
    - +.youtube.com
    - +.google.cn
    - +.googleapis.cn
    - +.googleapis.com
proxies:
- name: 测试节点
  type: trojan
  network: ws
  server: 194.76.18.129
  port: 443
  password: tg-fq521free
  skip-cert-verify: false
  udp: true
  sni: torjan.xn--xhq44j.eu.org
  ws-opts:
    headers:
      Host: torjan.xn--xhq44j.eu.org
    path: /
- name: 节点加速器 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 提醒您 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 您的Clash客户端 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 版本已过时 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 请访问我们的 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 官方网站 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 根据您的 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 设备和系统 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 下载新版本的客户端 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 客户端更新成功后 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 请重新更新订阅链接 | abshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 6df9071f-910e-472e-893b-e64055e9cc8c
  udp: true
- name: 节点加速器 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 提醒您 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 您的Clash客户端 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 版本已过时 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 请访问我们的 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 官方网站 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 根据您的 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 设备和系统 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 下载新版本的客户端 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 客户端更新成功后 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 请重新更新订阅链接 | mkshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 27c3f3a1-da86-4823-9e05-4b09986b5bf8
  udp: true
- name: 节点加速器 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 提醒您 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 您的Clash客户端 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 版本已过时 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 请访问我们的 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 官方网站 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 根据您的 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 设备和系统 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 下载新版本的客户端 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 客户端更新成功后 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 请重新更新订阅链接 | toshare5
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: e95c1547-4575-4c4e-b5c9-12b574291847
  udp: true
- name: 节点加速器 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 提醒您 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 您的Clash客户端 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 版本已过时 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 请访问我们的 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 官方网站 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 根据您的 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 设备和系统 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 下载新版本的客户端 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 客户端更新成功后 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 请重新更新订阅链接 | abshare3
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 33230e4f-0d4d-4568-8f01-6ccc0d447e77
  udp: true
- name: 节点加速器 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 提醒您 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 您的Clash客户端 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 版本已过时 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 请访问我们的 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 官方网站 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 根据您的 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 设备和系统 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 下载新版本的客户端 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 客户端更新成功后 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 请重新更新订阅链接 | tolinkshare2
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 1852c003-1178-48f6-afdb-a72e911ad1dd
  udp: true
- name: 节点加速器 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 提醒您 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 您的Clash客户端 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 版本已过时 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 请访问我们的 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 官方网站 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 根据您的 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 设备和系统 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 下载新版本的客户端 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 客户端更新成功后 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
- name: 请重新更新订阅链接 | mksshare
  type: ss
  server: 127.0.0.1
  port: '1080'
  cipher: aes-128-gcm
  password: 47da6718-6903-477a-814d-3b86131afa1e
  udp: true
proxy-groups:
- name: 代理选择
  type: select
  proxies:
  - 负载均衡
  - 手动选择
  - 故障转移
  - DIRECT
- name: 手动选择
  type: select
  proxies: &id001
  - 测试节点
  - 节点加速器 | abshare
  - 提醒您 | abshare
  - 您的Clash客户端 | abshare
  - 版本已过时 | abshare
  - 请访问我们的 | abshare
  - 官方网站 | abshare
  - 根据您的 | abshare
  - 设备和系统 | abshare
  - 下载新版本的客户端 | abshare
  - 客户端更新成功后 | abshare
  - 请重新更新订阅链接 | abshare
  - 节点加速器 | mkshare3
  - 提醒您 | mkshare3
  - 您的Clash客户端 | mkshare3
  - 版本已过时 | mkshare3
  - 请访问我们的 | mkshare3
  - 官方网站 | mkshare3
  - 根据您的 | mkshare3
  - 设备和系统 | mkshare3
  - 下载新版本的客户端 | mkshare3
  - 客户端更新成功后 | mkshare3
  - 请重新更新订阅链接 | mkshare3
  - 节点加速器 | toshare5
  - 提醒您 | toshare5
  - 您的Clash客户端 | toshare5
  - 版本已过时 | toshare5
  - 请访问我们的 | toshare5
  - 官方网站 | toshare5
  - 根据您的 | toshare5
  - 设备和系统 | toshare5
  - 下载新版本的客户端 | toshare5
  - 客户端更新成功后 | toshare5
  - 请重新更新订阅链接 | toshare5
  - 节点加速器 | abshare3
  - 提醒您 | abshare3
  - 您的Clash客户端 | abshare3
  - 版本已过时 | abshare3
  - 请访问我们的 | abshare3
  - 官方网站 | abshare3
  - 根据您的 | abshare3
  - 设备和系统 | abshare3
  - 下载新版本的客户端 | abshare3
  - 客户端更新成功后 | abshare3
  - 请重新更新订阅链接 | abshare3
  - 节点加速器 | tolinkshare2
  - 提醒您 | tolinkshare2
  - 您的Clash客户端 | tolinkshare2
  - 版本已过时 | tolinkshare2
  - 请访问我们的 | tolinkshare2
  - 官方网站 | tolinkshare2
  - 根据您的 | tolinkshare2
  - 设备和系统 | tolinkshare2
  - 下载新版本的客户端 | tolinkshare2
  - 客户端更新成功后 | tolinkshare2
  - 请重新更新订阅链接 | tolinkshare2
  - 节点加速器 | mksshare
  - 提醒您 | mksshare
  - 您的Clash客户端 | mksshare
  - 版本已过时 | mksshare
  - 请访问我们的 | mksshare
  - 官方网站 | mksshare
  - 根据您的 | mksshare
  - 设备和系统 | mksshare
  - 下载新版本的客户端 | mksshare
  - 客户端更新成功后 | mksshare
  - 请重新更新订阅链接 | mksshare
- name: 负载均衡
  type: load-balance
  url: https://cp.cloudflare.com/generate_204
  interval: 30
  strategy: consistent-hashing
  proxies: *id001
- name: 故障转移
  type: fallback
  url: https://cp.cloudflare.com/generate_204
  interval: 30
  proxies: *id001
- name: 漏网之鱼
  type: select
  proxies:
  - 代理选择
  - DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
rules:
- RULE-SET,reject,REJECT
- RULE-SET,apple,DIRECT
- RULE-SET,applications,DIRECT
- RULE-SET,cncidr,DIRECT
- RULE-SET,icloud,DIRECT
- RULE-SET,lancidr,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,proxy,代理选择
- RULE-SET,gfw,代理选择
- RULE-SET,google,代理选择
- RULE-SET,telegramcidr,代理选择
- RULE-SET,tld-not-cn,代理选择
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,漏网之鱼
